In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [21]:
dataset = pd.read_csv('csgo_steam_reviews.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [22]:
print(x)

[[133848242 'english'
  "Pretty good game all around.\nGreat game! I would recommend 10 and up because there is some blood but if you don't mind a splatter or two then you should be good."
  ... 44277 1075 44277]
 [133848123 'english' 'haha smiriva me\n' ... 2169 2169 2169]
 [133848052 'english' 'full of cheaterts roblox has better anti cheat'
  ... 15619 1976 15603]
 ...
 [131858525 'english' 'Yes.' ... 24054 325 23256]
 [131858289 'english' 'click head nothing happen' ... 9097 250 8242]
 [131858148 'english' 'good' ... 63228 10 62434]]


In [23]:
print(y)

['2023-03-01 09:04:32' '2023-03-01 09:16:29' '2023-03-01 09:15:00' ...
 '2023-02-27 21:32:04' '2023-02-28 16:06:13' '2023-02-19 18:36:17']


In [24]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [25]:
print(x)

[[133848242 'english'
  "Pretty good game all around.\nGreat game! I would recommend 10 and up because there is some blood but if you don't mind a splatter or two then you should be good."
  ... 44277 1075 44277]
 [133848123 'english' 'haha smiriva me\n' ... 2169 2169 2169]
 [133848052 'english' 'full of cheaterts roblox has better anti cheat'
  ... 15619 1976 15603]
 ...
 [131858525 'english' 'Yes.' ... 24054 325 23256]
 [131858289 'english' 'click head nothing happen' ... 9097 250 8242]
 [131858148 'english' 'good' ... 63228 10 62434]]


In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 0.0 ... 44277 1075 44277]
 [0.0 0.0 0.0 ... 2169 2169 2169]
 [0.0 0.0 0.0 ... 15619 1976 15603]
 ...
 [0.0 0.0 1.0 ... 24054 325 23256]
 [0.0 1.0 0.0 ... 9097 250 8242]
 [1.0 0.0 0.0 ... 63228 10 62434]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[14717 14884 14864 ...  7921  9370  2847]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 ... 48484 1887 46786]
 [0.0 0.0 0.0 ... 6289 0 5964]
 [0.0 0.0 0.0 ... 31789 1539 29784]
 ...
 [0.0 0.0 0.0 ... 7853 888 4668]
 [0.0 0.0 0.0 ... 129595 1749 129486]
 [0.0 0.0 0.0 ... 3986 1484 1222]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 ... 5241 545 1699]
 [0.0 0.0 0.0 ... 58713 846 58172]
 [0.0 0.0 0.0 ... 1636 636 1275]
 ...
 [0.0 0.0 0.0 ... 2082 499 810]
 [0.0 0.0 0.0 ... 24248 193 24055]
 [0.0 0.0 0.0 ... 39973 0 39973]]


In [ ]:
print(y_train)

[ 9364   395 14109 ... 14068 11877  7644]


In [ ]:
print(y_test)

[10552 11756 10696 ... 14363  3249   219]


In [39]:
import pandas as pd

# Mengambil kolom dengan data string
categorical_cols = [3]
x_train_categorical = x_train[:, categorical_cols]
x_test_categorical = x_test[:, categorical_cols]

# Melakukan One-Hot Encoding pada data string
ohe = pd.get_dummies(pd.concat([pd.DataFrame(x_train_categorical), pd.DataFrame(x_test_categorical)]))
x_train_ohe = ohe[:len(x_train_categorical)]
x_test_ohe = ohe[len(x_train_categorical):]

# Menggabungkan kembali data numerik dengan hasil One-Hot Encoding
x_train_processed = np.hstack((x_train[:, :3], x_train_ohe.values, x_train[:, 4:]))
x_test_processed = np.hstack((x_test[:, :3], x_test_ohe.values, x_test[:, 4:]))


c:\Users\Dewandra R\anaconda3\lib\site-packages\pandas\core\algorithms.py:798: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  uniques = Index(uniques)


In [41]:

print(x_train)

[[0.0 0.0 0 ... 48484 1887 46786]
 [0.0 0.0 0 ... 6289 0 5964]
 [0.0 0.0 0 ... 31789 1539 29784]
 ...
 [0.0 0.0 0 ... 7853 888 4668]
 [0.0 0.0 0 ... 129595 1749 129486]
 [0.0 0.0 0 ... 3986 1484 1222]]


In [42]:
print(x_test)

[[0.0 0.0 0 ... 5241 545 1699]
 [0.0 0.0 0 ... 58713 846 58172]
 [0.0 0.0 0 ... 1636 636 1275]
 ...
 [0.0 0.0 0 ... 2082 499 810]
 [0.0 0.0 0 ... 24248 193 24055]
 [0.0 0.0 0 ... 39973 0 39973]]
